version: "3"

services:
  web:
    build: .
    restart: always
    command: python async-api/server.py
    ports:
      - 8080:8080
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: async
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data: